# Tensors

In [1]:
import tensorflow as tf
import numpy as np

ModuleNotFoundError: No module named 'tensorflow'

In [7]:
x = tf.constant(5.0)

In [8]:
x

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [5]:
x.shape

TensorShape([])

In [9]:
x.dtype

tf.float32

In [10]:
x.numpy()

5.0

In [11]:
x

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [12]:
result = x + 10
result

<tf.Tensor: shape=(), dtype=float32, numpy=15.0>

In [13]:
result1 = x-2
result1

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [14]:
x1 = tf.constant([1.0, 2.0, 3.0])
x1

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [15]:
x1.dtype

tf.float32

In [16]:
result2 = x1 + 10
result2

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([11., 12., 13.], dtype=float32)>

In [17]:
result3 = x1-1
result3

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0., 1., 2.], dtype=float32)>

In [18]:
x3 = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
x3

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [19]:
x3.shape

TensorShape([2, 3])

In [20]:
x3.dtype

tf.float32

In [26]:
x4 = tf.constant([1,2,3])
x4

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [27]:
x4.dtype

tf.int32

In [28]:
new_x4 = tf.cast(x4, tf.float32)
new_x4

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [29]:
new_x4.dtype

tf.float32

In [30]:
y1 = tf.constant([1,2,3])
y2 = tf.constant([4,5,6])

In [32]:
result_y1= tf.add(y1, y2)
result_y1

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9])>

In [34]:
result_y2 = tf.multiply(y1, y2)
result_y2

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4, 10, 18])>

In [35]:
y1

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [37]:
arr_y1 = y1.numpy()
arr_y1

array([1, 2, 3])

In [38]:
tensor_arr = tf.convert_to_tensor(arr_y1)
tensor_arr

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [39]:
y1

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [40]:
np.sqrt(y1)

array([1.        , 1.41421356, 1.73205081])

In [41]:
np.square(y1)

array([1, 4, 9], dtype=int32)

In [42]:
zero = tf.zeros([3,5])
zero

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [44]:
ones = tf.ones([3,5])
ones

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [45]:
tf_reshaped = tf.reshape(ones, (5,3))

In [46]:
tf_reshaped

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>